---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
  namespace: jenkins
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
  - name: generic
    targetPort: 8080
    port: 8080
  - protocol: TCP
    name: http-api
    port: 80
    targetPort: 8080
  - protocol: TCP
    name: https-api
    port: 443
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-nlp
  namespace: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins-server
  ports:
  - port: 50000
    targetPort: 50000
