name: Output Information
on: 
  workflow_dispatch: # only works in the default branch if not specified
  push:
    branches: 
    - feature/github-workflow
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: Output GitHub context
      run: echo "${{ toJson(github) }}"
